### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by zhaoleo1998** [aravind1338/Stats506_public#2]
Hello, 

I just looked through your repo. And I have some suggestions for you:

- You didn't include your groupmates' repo address 
- And in your week4_part1. Rmd file, I recommend you to start a new line after each pipe sign for better readiness.
For example, you can write the following line as 
Orange %>% group_by(age) %>% mutate(zscore = (circumference - mean(circumference))/sd(circumference))

Orange %>% 
     group_by(age) %>%
     mutate(zscore = (circumference - mean(circumference))/sd(circumference))

Leo

**Comment by aravind1338** [comment]
Thanks for the suggestions!
